"""add_security_findings_table

Revision ID: 03fdf5c62169
Revises: b2a6666b69f5
Create Date: 2026-07-02 11:53:16.652585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03fdf5c62169'
down_revision: Union[str, None] = 'b2a6666b69f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('owasp_category', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('covered', 'gap', 'not_applicable', name='security_finding_status'), nullable=False),
    sa.Column('risk_level', sa.Enum('critical', 'high', 'medium', 'low', name='security_risk_level'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_findings_story_id'), 'security_findings', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_findings_story_id'), table_name='security_findings')
    op.drop_table('security_findings')
    # ### end Alembic commands ###
