"""add_automation_scripts_table

Revision ID: b2a6666b69f5
Revises: 3d4f80ea9f84
Create Date: 2026-07-02 03:46:42.556794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a6666b69f5'
down_revision: Union[str, None] = '3d4f80ea9f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('test_case_id', sa.String(), nullable=True),
    sa.Column('framework', sa.Enum('playwright', 'robot', name='automation_framework'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('health_status', sa.Enum('healthy', 'flaky', 'broken', name='script_health_status'), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('failure_root_cause', sa.String(), nullable=True),
    sa.Column('ci_run_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_scripts_story_id'), 'automation_scripts', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_scripts_story_id'), table_name='automation_scripts')
    op.drop_table('automation_scripts')
    # ### end Alembic commands ###
